import re

from playwright.sync_api import expect

from utils.config import Config
from utils.entity_navigation import LEAD_BUCKET, MY_DEALS_BUCKET, open_bucket_record, verify_bucket_record_visible
from utils.toast import Toast
from utils.wait_helpers import wait_for_page_ready


class NotesPage:

    def __init__(self, page):
        self.page = page

    # Navigation
    def open(self):
        self.page.goto(Config.BASE_URL)
        wait_for_page_ready(self.page)

    def open_lead(self, lead_name: str, bucket=LEAD_BUCKET):
        open_bucket_record(self.page, bucket, lead_name)

    def open_notes_tab(self):
        self.page.get_by_role("tab", name="Notes").click()

    def _notes_tabpanel(self):
        return self.page.get_by_role("tabpanel", name="Notes")

    def _add_note_form(self):
        return self._notes_tabpanel().locator("form")

    def _add_note_save_button(self):
        return self._add_note_form().get_by_role("button", name="Save Notes")

    def _add_note_cancel_button(self):
        return self._add_note_form().get_by_role("button", name="Cancel")

    # Add Note
    def dismiss_add_note_form_if_open(self) -> None:
        """Close an in-progress add-note form so the Add Note button is available."""
        save_notes = self._add_note_save_button()
        if save_notes.count() == 0 or not save_notes.is_visible():
            return
        cancel = self._add_note_cancel_button()
        expect(cancel).to_be_visible(timeout=10000)
        cancel.click()
        expect(self._notes_tabpanel().get_by_role("button", name="Add Note")).to_be_visible(
            timeout=10000
        )

    def click_add_note(self):
        save_notes = self._add_note_save_button()
        if save_notes.count() > 0 and save_notes.is_visible():
            return
        add_btn = self._notes_tabpanel().get_by_role("button", name="Add Note")
        expect(add_btn).to_be_visible(timeout=30000)
        add_btn.click()

    def enter_note(self, note_text: str):
        self.page.locator(".tiptap").fill(note_text)

    def clear_note(self):
        self.enter_note("")

    def enter_whitespace_note(self):
        """Fill the rich-text editor with spaces so isRichTextEmpty rejects it."""
        self.enter_note("   ")

    def apply_formatting(self):
        # Generated by codegen
        self.page.get_by_role("button").filter(
            has_text=re.compile(r"^$")
        ).nth(2).click()

        self.page.get_by_role("button").filter(
            has_text=re.compile(r"^$")
        ).nth(2).click()

        self.page.get_by_role("button").filter(
            has_text=re.compile(r"^$")
        ).nth(3).click()

    def select_heading(self, heading: str):
        self.page.get_by_role(
            "tabpanel",
            name="Notes"
        ).get_by_role("combobox").click()

        self.page.get_by_role("option", name=heading).click()

    def select_note_status(self, status: str):
        self.page.get_by_text(status).click()

    def save_note(self):
        self._add_note_save_button().click()

    def save_note_successfully(self):
        self.save_note()
        Toast(self.page).assert_message("Notes added successfully")

    def _note_card_by_text(self, note_text: str):
        """Target a single note card; use last match when duplicate text exists."""
        return (
            self.page.locator("[class*='transition-shadow']")
            .filter(has_text=note_text)
            .last
        )

    def _open_note_menu(self, note_text: str):
        note_card = self._note_card_by_text(note_text)
        expect(note_card).to_be_visible(timeout=15000)
        note_card.locator("button[aria-haspopup='menu']").click()


    # Edit Note
    def edit_note(self, note_text: str, updated_note: str):
        self._open_note_menu(note_text)
        self.page.get_by_role("menuitem", name="Edit").click()

        editor = self.page.locator(".tiptap").last
        editor.wait_for(state="visible")
        editor.fill(updated_note)

        self.page.get_by_role("button", name="Update").click()
        Toast(self.page).assert_message("Notes updated successfully")

    # Delete Note
    def delete_note(self, note_text: str):
        self._open_note_menu(note_text)
        self.page.get_by_role("menuitem", name="Delete").click()
        self.page.get_by_role("button", name="Delete").click()
        Toast(self.page).assert_message("Notes deleted successfully")
        expect(self._note_card_by_text(note_text)).to_have_count(0, timeout=15000)

    def move_to_sales(self):
        self.page.get_by_role("button", name="Move to Sales").click()
        self.page.get_by_role("alertdialog").get_by_role("button", name="Yes").click()

    def verify_moved_to_sales(self):
        expect(self.page).to_have_url(re.compile(r"/sales/"), timeout=30000)
        Toast(self.page).assert_message("Lead updated successfully")

    def verify_lead_in_my_deals(self, deal_name: str):
        verify_bucket_record_visible(self.page, MY_DEALS_BUCKET, deal_name)